### ISSUE TITLE
Allow tables to be assigned to cdm reference (if they are tables with the same source)

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/omopgenerics#105]
@catalamarti  e.g. allowing the following code to continue to work (which would allow CodelistGenerator to be released in a way that will already be compatable)

```
  cdm$achilles_analysis <- dplyr::tbl(db, "achilles_analysis")
  cdm$achilles_results <- dplyr::tbl(db, "achilles_results")
  cdm$achilles_results_dist <- dplyr::tbl(db, "achilles_results_dist")
```

**Comment by catalamarti** [comment]
So I have implemented this for local tables #108
We can do sth similar with cdm_connector, but we have to be careful with naming because the function will be exported and we do not want to be confused with `insertTable` for the moment I've called it `insertFromSource` but open to suggestions @edward-burn

**Comment by catalamarti** [comment]
I've added the methods for db_cdm in: https://github.com/darwin-eu-dev/CDMConnector/pull/369
(sorry to mix things in a PR, but otherwise tests were not passing)
If you install that branch and last version of omopgenerics it should work.
Let's agree an appropriated name but for me it is good to go @edward-burn

**Comment by edward-burn** [comment]
Awesome!
