### ISSUE TITLE
agree on cdmReference class

### ISSUE THREAD

**Issue by catalamarti** [darwin-eu-dev/OMOPGenerics#3]

**Comment by catalamarti** [comment]
cdmReference will be a method

To agree details

**Comment by edward-burn** [comment]
One question here is whether we allow additional tables (and if we have any requirements around them). I'm in favour of allowing this because it would mean it's easy for users to include things like achilles tables, pregnancy extension, derived tables we create during an analysis, etc. For me I think we can see this as analogous to how we allow extra columns to be present in cohort tables etc. But I'm not sure if @ablack3 would agree?

**Comment by ablack3** [comment]
I'm ok with additional tables but I think it would be nice to have some bounds around what those are. To me the CDM object is supposed to be an OMOP CDM. For example, Theresa was getting an error a while back because her CDM had only cohort tables and no actual CDM tables which I never expected. So my question is what is the difference between a CDM reference and simply a collection of tables?

**Comment by catalamarti** [comment]
try constructor + constructor without interacting with database
